### ISSUE TITLE
Incorrect output 

### ISSUE THREAD

**Issue by toxaq** [jsmreese/moment-duration-format#20]
moment.duration(600, 'seconds').format()
     -> "10"
     moment.duration(601, 'seconds').format()
     -> "10:01"
     moment.duration(602, 'seconds').format()
     -> "10:02"
     moment.duration(603, 'seconds').format()
     -> "10:02" #<- WAT
     moment.duration(604, 'seconds').format()
     -> "10:04"

Am I doing something wrong?

**Comment by jsmreese** [comment]
You must be using moment.js version 2.8.0, 2.8.1, or 2.8.2, which had issues with the `as` and `as*` methods (see https://github.com/jsmreese/moment-duration-format/issues/13). Hopefully you've upgraded to a more recent version of moment.js version since then, which will fix the issue.

I need to use the `as` method instead of `get` because in addition to the rounded whole value, I sometimes need to know the fractional component of the resulting value.

**Comment by toxaq** [comment]
Right you are. Thanks for the update and for the work you've done on this project, it's greatly appreciated.
