### ISSUE TITLE
Padding/Leading Zeros doesn't work?

### ISSUE THREAD

**Issue by romgen** [jsmreese/moment-duration-format#24]
I'm using the plugin like this:

var test = moment.duration(3562296); // milliseconds
test.format("HH:mm:ss");

The result is:
"59:22"

The result should be:
"59:22:00"

**Comment by romgen** [comment]
Nevermind: trim="false" should be standard!

Why would you have trum="left" as standard? If I want no leading zeros, why would I define the template as "HH" and not as "H"? or something? 

It doesn't make any sense.

**Comment by jsmreese** [comment]
Ahh, you meant the expected result should be `00:59:22`.

There are lots of use cases here. The default is to output as little text as possible because in general, leading zeros just obscure the actual value and require a user to spend more time parsing the representation to discern its meaning.

Just some of the ways you might want that value to be output (all of which are possible with this plugin):
```
00:59:22
0:59:22
59:22
59:22.2
59:22.3
59:22.29
00:59:22.29
...
```

Also, using `h` versus `hh` in a template does have meaning in how the output is trimmed/displayed when the most significant token has a zero value.

```
moment.duration(9, "minutes").format("hh:mm:ss");
// 09:00
moment.duration(9, "minutes").format("h:mm:ss");
// 9:00
```

**Comment by romgen** [comment]
I understand, but if I specify the format to be "HH:mm:ss" i ecpect the plugin to give me a format as I requested. Trimming should always be optional, not standard.

I work for a TV broadcasting network and I've never seen any application (Apple Final Cut Pro X, Adobe Premiere - you name it) where the duration was trimmed by default because the user "spends more time to parse". O.o

Nontheless, good plugin and thank you :-)
