### ISSUE TITLE
'1d 0h' being displayed

### ISSUE THREAD

**Issue by pedroteixeira** [jsmreese/moment-duration-format#25]
> `moment.duration(24, 'hours').format('d[d] h[h]')`
> `"1d 0h"`

But from the docs, I thought the 0h would be omitted by default:
expected: `"1d"`

is this intended, and is there any extra options to change it?
thanks!

**Comment by ocharles** [comment]
I believe the default is to trim from the left. What happens if you trim from the right?

**Comment by pedroteixeira** [comment]
trim right removes the 'h':

```js moment.duration(24, 'hours').format('d[d] h[h]', { trim: "right" })
"1d 0"
```

**Comment by mitar** [comment]
Yes, this does not work:

```
moment.duration({hours: 4, minutes: 0}).abs().format('w [weeks] d [days] h [hours] m [minutes]', {trim: 'right'})
"0 weeks 0 days 4 hours 0"
```

It would be great to be able to trim from both sides.

**Comment by mitar** [comment]
I would suggest to simply trim all 0 values.

**Comment by jsmreese** [comment]
Sorry for the delay on this... changed my notification settings for my new job back in March and I've missed a lot of stuff on this project.

Trimming is designed to drop zero values for higher magnitude units.
So instead of `0d 1h`, just output `1h`.

I understand what you're asking for, and @mitar 's suggestion would probably make a good feature. I'll take a look at how to add it.

**Comment by mitar** [comment]
Later on I implemented it [myself here](https://github.com/mitar/council-app/blob/master/packages/ui-components/base.coffee#L161). Feel free to use ideas from it.

**Comment by carueda** [comment]
+1

**Comment by albertpak** [comment]
:+1: , also would be nice to show if its just seconds that if its less than a minute, to show `<1m`, i.e if it's 25 seconds, then display `<1m`

**Comment by t1mmen** [comment]
This issue is also related to https://github.com/jsmreese/moment-duration-format/issues/45

I'd love to see the feature implemented as per @mitar's suggestion!

**Comment by mitar** [comment]
I updated a link to my code implementation above. It works great for me.

**Comment by jsmreese** [comment]
I've pushed a version of this plugin to the `master` branch that implements `trim: "both"` as well as `largest`.

I'll take a look at the other API ideas here... trimming all zero-value tokens, and comma-separating output in a locale-sensitive way. `trim: "zero"` would be simple enough in my updated code.

**Comment by jsmreese** [comment]
Closing this issue since `trim: "both"` is now available on the master branch.

FYI that I'm working on an updated, more flexible trim API right now. Nothing that already works will break with the new options, but you'll have more trim flexibility.

See my comment here: https://github.com/jsmreese/moment-duration-format/issues/64#issuecomment-349027315

@albertpak interesting suggestion with outputting `<1m`. I'll take a look at that.

**Comment by jsmreese** [comment]
@albertpak, the version I just pushed implements minValue and maxValue, which lets you generate output like `< 1 minute` and `> 60 days`.
