### ISSUE TITLE
i18n usages?

### ISSUE THREAD

**Issue by stefantalen** [jsmreese/moment-duration-format#26]
Can I use the Moment locales with this plugin? And if so, how?

I'd like to have a format like: **4 hours 58 minutes**.

I tried

```
moment.duration(17880, 'seconds').format("hh mm");
```

but that leaves me with **04 58**

Edit:

I've got it working now by using this:

```
moment.duration(17880, 'seconds').format("h ["+ moment._locale._relativeTime.hh.slice(3) +"] m ["+ moment._locale._relativeTime.mm.slice(3) +"]");
```

if there is native support via this duration plugin please let me know.

**Comment by mnoble01** [comment]
+1 is this possible?

**Comment by jsmreese** [comment]
Sorry for the delay... changed my github notifications when I started a new job in March and didn't realize I'd been ignoring this project for 8 months!

I've been pondering how best to support this sort of thing for a while, and haven't come up with anything better than what you've done.

`moment._locale._relativeTime` has some of what's needed for basic i18n output like `4 hours 31 minutes`, but it falls down even at seconds where there's no singular/plural. And it has no support for abbreviated names. And no support for default time formats -- which could be parsed from `longDateFormat.LT` and `LTS`, but that would be pretty hackish across languages.

Just noticed https://github.com/moment/moment-cldr... the best solution might lie in that direction? Dunno.

**Comment by polo2ro** [comment]
hi, i had the same problem and solved it by injecting my own localized strings. This leave me with one related problem: the decimal separator.
In france we use the coma but i found no way to set a custom decimal separator

**Comment by polo2ro** [comment]
just saw this commit in the dev branch : https://github.com/jsmreese/moment-duration-format/commit/60c7194cf7855dcd912c698520b638f43c4c5f6e

il will test it

**Comment by JonathanFowlke** [comment]
Any progress on this issue?  I would like to use this plugin, but this issue is holding me back.

**Comment by jsmreese** [comment]
I'm working on this right now. I've extended the Moment.locale object so that durations can have a complete set of localized unit names that can be auto-singularized and even auto-populated.

e.g. `m __, s __` --> `1 minute, 1 second` and `y _, d _` --> `1 year, 37 days`

And if the units of the current locale are detected in the format string, they'd be auto-singularized, too.

e.g. `m [minutes], s [seconds]` --> `1 minute, 37 seconds`

I'm looking at using `toLocaleString` to render all numerical output to make this fully support i18n. Leaning towards outputting numbers in the user's locale (https://stackoverflow.com/questions/25725882/locale-detection-with-moment-js) with the option to force numbers to be rendered in moment's locale (user's locale and moment's locale are not necessarily the same...)

Any thoughts on this approach would be appreciated. This would also address #74 and #70.
