### ISSUE TITLE
Error: When loading with Browserify

### ISSUE THREAD

**Issue by four43** [jsmreese/moment-duration-format#29]
I am getting the error with Moment 2.9.0 and 2.10.0 when loading this library via browserify:

Uncaught TypeError: Cannot set property 'format' of undefined

From: https://github.com/jsmreese/moment-duration-format/blob/master/lib/moment-duration-format.js#L202

Thoughts?

Thanks for the work on this, it works wonderfully on the server side!

**Comment by four43** [comment]
Seems to work great when loading in the browser using plain ol <script> tags, moment then moment-duration-format, as your docs say... I wonder what browserify is doing that's funky...

**Comment by andreialecu** [comment]
The problem here is that when using browserify or webpack, moment doesn't attach to window.

Adding `window.moment = require('moment');` or `var moment = require('moment');` according to https://github.com/jsmreese/moment-duration-format/blob/master/lib/moment-duration-format.js#L193 prior to requiring this plugin will fix it.

This should be documented better since it is not very intuitive.

**Comment by four43** [comment]
Way to pick up on this relatively old issue. Thanks @andreialecu, I'll have to give it a shot.

**Comment by jsmreese** [comment]
Sorry for the delay. Changed my github notifications when I started a new job in March and didn't realize I've been ignoring this project for 8 months.

I'm pretty sure that what you need is on my dev branch added in 5698eccd2c1e8717e736146b7a6b464b2625508d. An initializer function is exported so that you can initialize moment-duration-format on any moment instance you wish.

I'll try to get a new version wrapped up and published soonish.

**Comment by four43** [comment]
Perfect, thanks @jsmreese

**Comment by pjm17971** [comment]
Any chance of getting a new version of this library up on npm that resolves the above issues? (see the above issue from @navtej)
