### ISSUE TITLE
Trim: 'right' works incorrectly

### ISSUE THREAD

**Issue by jrencz** [jsmreese/moment-duration-format#45]
``` js
moment.duration(2, 'days').format('d[ days] h[ hours]');
// 2 days 0 hours
```

I'd like to be able to drop the `0 hours part`
I tried `{trim: 'right'}`:

``` js
moment.duration(2, 'days').format({
  template: 'd[ days] h[ hours]',
  trim: 'right',
});
// 2 days 0
```

I expected it to produce `2 days` not `2 days 0`.
It's either a bug or `{trim: 'right'}` is not meant for what I tried to use it (although the name makes me think it is)

**Comment by jrencz** [comment]
FYI:
For now i managed to make it right using:
```js
moment
  .duration(2, 'days')
  .format('d[ days] h[ hours]')
  .replace(/\s0\s\w+/g, '')
```
but it's far from a general solution

**Comment by jsmreese** [comment]
`trim: "right"` is meant for trimming when your values are reversed, e.g. `2 hours 0 days`.

I've just pushed a version of this plugin to the `master` branch that implements `trim: "both"`, which will do what you want. Hopefully I'll have it published soon.

**Comment by jsmreese** [comment]
Closing this issue since `trim: "both"` is now available on the master branch.

FYI that I'm working on an updated, more flexible trim API right now. Nothing that already works will break with the new options, but you'll have more trim flexibility.

See my comment here: https://github.com/jsmreese/moment-duration-format/issues/64#issuecomment-349027315
