### ISSUE TITLE
Trim both

### ISSUE THREAD

**Issue by grimurd** [jsmreese/moment-duration-format#46]
I want to trim a date from both sides, so that a duration that can range from a minute to a couple of months won't show
"0 months 0 days 1 hour 0 minutes 0 seconds" but instead just shows "1 hour"

**Comment by jektify** [comment]
+1 this would be awesome

**Comment by jsmreese** [comment]
Closing this issue since `trim: "both"` is now available on the master branch.

FYI that I'm working on an updated, more flexible trim API right now. Nothing that already works will break with the new options, but you'll have more trim flexibility.

See my comment here: https://github.com/jsmreese/moment-duration-format/issues/64#issuecomment-349027315
